// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rAYL6Et4dcj7gxQck53y1m7LKpmojSo',
    appId: '1:631440667955:web:1626bcc79968d219ee7a46',
    messagingSenderId: '631440667955',
    projectId: 'calmademic-25',
    authDomain: 'calmademic-25.firebaseapp.com',
    storageBucket: 'calmademic-25.firebasestorage.app',
    measurementId: 'G-7EEN1XDWHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP6IYwRYD-sDDVLMGi9YgSdHtU6XNw4t4',
    appId: '1:631440667955:android:cf85d7a6f0fc9954ee7a46',
    messagingSenderId: '631440667955',
    projectId: 'calmademic-25',
    storageBucket: 'calmademic-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJSYyHP_CPwYalZ6_OcIWUhX39RR4RrQ',
    appId: '1:631440667955:ios:daff1f3580ad3b4cee7a46',
    messagingSenderId: '631440667955',
    projectId: 'calmademic-25',
    storageBucket: 'calmademic-25.firebasestorage.app',
    androidClientId: '631440667955-o5ojl8r8mc4jnbcj7h1vvp0oir3ipiph.apps.googleusercontent.com',
    iosClientId: '631440667955-0cfs4nnefi3j28315ntee9ohlc16gnft.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickCounter',
  );

}